const testData = {
  businesses: [
    {
      id: 'i50BEr4Pq6-D8tmsegmVyA',
      alias: 'the-table-san-jose',
      name: 'The Table',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/Y70NLnzrDZ-vkW9xiTAM1Q/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/the-table-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 3614,
      categories: [
        {
          alias: 'newamerican',
          title: 'New American',
        },
        {
          alias: 'breakfast_brunch',
          title: 'Breakfast & Brunch',
        },
        {
          alias: 'salad',
          title: 'Salad',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.308203,
        longitude: -121.901284,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '1110 Willow St',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95125',
        country: 'US',
        state: 'CA',
        display_address: ['1110 Willow St', 'San Jose, CA 95125'],
      },
      phone: '+14086387911',
      display_phone: '(408) 638-7911',
      distance: 1712.3326119685419,
    },
    {
      id: 'YwBw5RE9BCB1Kuq863t1hg',
      alias: 'kings-fish-house-san-jose-san-jose',
      name: "King's Fish House - San Jose",
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/CwJIeZ4L_JWpSdpokmOzpg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/kings-fish-house-san-jose-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1925,
      categories: [
        {
          alias: 'seafood',
          title: 'Seafood',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.325395,
        longitude: -121.945348,
      },
      transactions: [],
      price: '$$$',
      location: {
        address1: '2855 Stevens Creek Blvd',
        address2: 'Ste 1820',
        address3: null,
        city: 'San Jose',
        zip_code: '95128',
        country: 'US',
        state: 'CA',
        display_address: ['2855 Stevens Creek Blvd', 'Ste 1820', 'San Jose, CA 95128'],
      },
      phone: '+16696993474',
      display_phone: '(669) 699-3474',
      distance: 5491.10348995097,
    },
    {
      id: 'rjUOwXNxsg0tstFssAjfsQ',
      alias: 'luna-mexican-kitchen-the-alameda-san-jose',
      name: 'LUNA Mexican Kitchen - The Alameda',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/JjzG0auXHdUing7hHn7keQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/luna-mexican-kitchen-the-alameda-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 2612,
      categories: [
        {
          alias: 'mexican',
          title: 'Mexican',
        },
        {
          alias: 'breakfast_brunch',
          title: 'Breakfast & Brunch',
        },
        {
          alias: 'vegetarian',
          title: 'Vegetarian',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.333944,
        longitude: -121.915297,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '1495 The Alameda',
        address2: '',
        address3: null,
        city: 'San Jose',
        zip_code: '95126',
        country: 'US',
        state: 'CA',
        display_address: ['1495 The Alameda', 'San Jose, CA 95126'],
      },
      phone: '+14083202654',
      display_phone: '(408) 320-2654',
      distance: 3299.44931867476,
    },
    {
      id: 'MlwoQuHxWozRFHeCeF7fZA',
      alias: 'orchard-city-kitchen-campbell',
      name: 'Orchard City Kitchen',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/hDl-2LrJev7K3XtBr_ni8g/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/orchard-city-kitchen-campbell?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 4431,
      categories: [
        {
          alias: 'newamerican',
          title: 'New American',
        },
        {
          alias: 'tapas',
          title: 'Tapas Bars',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.28820796640651,
        longitude: -121.93420216177606,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '1875 S Bascom Ave',
        address2: 'Ste 190',
        address3: '',
        city: 'Campbell',
        zip_code: '95008',
        country: 'US',
        state: 'CA',
        display_address: ['1875 S Bascom Ave', 'Ste 190', 'Campbell, CA 95008'],
      },
      phone: '+14083405285',
      display_phone: '(408) 340-5285',
      distance: 5372.4403591283635,
    },
    {
      id: 'fBCkn1-ZVVSF93nRMHnfHg',
      alias: 'paper-plane-san-jose-2',
      name: 'Paper Plane',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/CEzLkgkl5Tq3wynCVNGVXw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/paper-plane-san-jose-2?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1579,
      categories: [
        {
          alias: 'cocktailbars',
          title: 'Cocktail Bars',
        },
        {
          alias: 'newamerican',
          title: 'New American',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3350126347807,
        longitude: -121.889442006445,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '72 S 1st St',
        address2: null,
        address3: '',
        city: 'San Jose',
        zip_code: '95113',
        country: 'US',
        state: 'CA',
        display_address: ['72 S 1st St', 'San Jose, CA 95113'],
      },
      phone: '+14087132625',
      display_phone: '(408) 713-2625',
      distance: 2086.5440782198098,
    },
    {
      id: 'kOY-1i0jaW6Bb8as34sqwQ',
      alias: 'the-grandview-restaurant-san-jose',
      name: 'The Grandview Restaurant',
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/gsy_3gmpd7f_Y-Rey8RAbw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/the-grandview-restaurant-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1967,
      categories: [
        {
          alias: 'venues',
          title: 'Venues & Event Spaces',
        },
        {
          alias: 'steak',
          title: 'Steakhouses',
        },
        {
          alias: 'newamerican',
          title: 'New American',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3648315,
        longitude: -121.7640765,
      },
      transactions: ['pickup', 'restaurant_reservation'],
      price: '$$$$',
      location: {
        address1: '15005 Mount Hamilton Rd',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95140',
        country: 'US',
        state: 'CA',
        display_address: ['15005 Mount Hamilton Rd', 'San Jose, CA 95140'],
      },
      phone: '+14082518909',
      display_phone: '(408) 251-8909',
      distance: 11963.984768977882,
    },
    {
      id: 'wGBYKBR610I3K1_h4pHUrQ',
      alias: 'firehouse-no-1-gastropub-san-jose',
      name: 'Firehouse No.1 Gastropub',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/DZuE_RmnZ75_7RhNX2UCiA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/firehouse-no-1-gastropub-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1734,
      categories: [
        {
          alias: 'tradamerican',
          title: 'American',
        },
        {
          alias: 'pubs',
          title: 'Pubs',
        },
        {
          alias: 'gastropubs',
          title: 'Gastropubs',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.33607,
        longitude: -121.89426,
      },
      transactions: ['delivery'],
      price: '$$$',
      location: {
        address1: '69 N San Pedro St',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95110',
        country: 'US',
        state: 'CA',
        display_address: ['69 N San Pedro St', 'San Jose, CA 95110'],
      },
      phone: '+14082876969',
      display_phone: '(408) 287-6969',
      distance: 2321.8039805615704,
    },
    {
      id: 'TQEfj1-QhyWCJ29u3l9Kjw',
      alias: 'gen-korean-bbq-house-san-jose',
      name: 'Gen Korean BBQ House',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/i0PPexcMvpmXY1y65lJ31g/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/gen-korean-bbq-house-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 7942,
      categories: [
        {
          alias: 'korean',
          title: 'Korean',
        },
        {
          alias: 'bbq',
          title: 'Barbeque',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3872324410459,
        longitude: -121.885422354631,
      },
      transactions: [],
      price: '$$',
      location: {
        address1: '1628 Hostetter Rd',
        address2: 'Ste F',
        address3: '',
        city: 'San Jose',
        zip_code: '95131',
        country: 'US',
        state: 'CA',
        display_address: ['1628 Hostetter Rd', 'Ste F', 'San Jose, CA 95131'],
      },
      phone: '+14084772773',
      display_phone: '(408) 477-2773',
      distance: 7856.49136952106,
    },
    {
      id: '6Bsqo2SLjtSn_cwwD-4RAg',
      alias: 'black-sheep-brasserie-san-jose',
      name: 'Black Sheep Brasserie',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/dLAh6wG4TeNHbJueQ9J0Lw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/black-sheep-brasserie-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 688,
      categories: [
        {
          alias: 'newamerican',
          title: 'New American',
        },
        {
          alias: 'french',
          title: 'French',
        },
        {
          alias: 'brasseries',
          title: 'Brasseries',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3069625,
        longitude: -121.8994391,
      },
      transactions: [],
      price: '$$$',
      location: {
        address1: '1202 Lincoln Ave',
        address2: 'Ste 30',
        address3: '',
        city: 'San Jose',
        zip_code: '95125',
        country: 'US',
        state: 'CA',
        display_address: ['1202 Lincoln Ave', 'Ste 30', 'San Jose, CA 95125'],
      },
      phone: '+14088167251',
      display_phone: '(408) 816-7251',
      distance: 1663.0564401834956,
    },
    {
      id: 'OeePb_OQIgCnt3nO53XEtA',
      alias: 'claw-shack-san-jose',
      name: 'Claw Shack',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/unu8ZJqwt5M21gYcuh1Mbw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/claw-shack-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1530,
      categories: [
        {
          alias: 'cajun',
          title: 'Cajun/Creole',
        },
        {
          alias: 'seafood',
          title: 'Seafood',
        },
        {
          alias: 'chicken_wings',
          title: 'Chicken Wings',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.3732322,
        longitude: -121.873416,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '1696 Berryessa Rd',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95133',
        country: 'US',
        state: 'CA',
        display_address: ['1696 Berryessa Rd', 'San Jose, CA 95133'],
      },
      phone: '+14086496741',
      display_phone: '(408) 649-6741',
      distance: 6334.255217632937,
    },
    {
      id: 'cCKea_ufuGcxI14fhe84vw',
      alias: 'cha-cha-sushi-san-jose',
      name: 'Cha Cha Sushi',
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/Vh2q3mQ-IFmYQ_WYV9H9kQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/cha-cha-sushi-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 3955,
      categories: [
        {
          alias: 'sushi',
          title: 'Sushi Bars',
        },
        {
          alias: 'japanese',
          title: 'Japanese',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.2758545677726,
        longitude: -121.852952245369,
      },
      transactions: ['pickup'],
      price: '$$',
      location: {
        address1: '547 W Capitol Expy',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95136',
        country: 'US',
        state: 'CA',
        display_address: ['547 W Capitol Expy', 'San Jose, CA 95136'],
      },
      phone: '+14082652416',
      display_phone: '(408) 265-2416',
      distance: 5344.071278185195,
    },
    {
      id: 'TANWKEUxyZvNnWu_Yv0ARg',
      alias: 'the-breakfast-club-san-jose',
      name: 'The Breakfast Club',
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/Yhf4z3CgYtlZNMyctn6tOw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/the-breakfast-club-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 3900,
      categories: [
        {
          alias: 'breakfast_brunch',
          title: 'Breakfast & Brunch',
        },
        {
          alias: 'waffles',
          title: 'Waffles',
        },
        {
          alias: 'tradamerican',
          title: 'American',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3232907061724,
        longitude: -121.91422832132292,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '1432 W San Carlos St',
        address2: 'Ste 80',
        address3: null,
        city: 'San Jose',
        zip_code: '95126',
        country: 'US',
        state: 'CA',
        display_address: ['1432 W San Carlos St', 'Ste 80', 'San Jose, CA 95126'],
      },
      phone: '+14085647150',
      display_phone: '(408) 564-7150',
      distance: 2687.2216689344336,
    },
    {
      id: '3eKhFdXHvne3_YVjxfrTGQ',
      alias: 'fogo-de-chao-brazilian-steakhouse-san-jose-6',
      name: 'Fogo de Chão Brazilian Steakhouse',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/DWFemT5KPCv36LW1MUnpDw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/fogo-de-chao-brazilian-steakhouse-san-jose-6?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 4663,
      categories: [
        {
          alias: 'brazilian',
          title: 'Brazilian',
        },
        {
          alias: 'steak',
          title: 'Steakhouses',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3202585632998,
        longitude: -121.949787738762,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$$',
      location: {
        address1: '377 Santana Row',
        address2: 'Ste 1090',
        address3: '',
        city: 'San Jose',
        zip_code: '95128',
        country: 'US',
        state: 'CA',
        display_address: ['377 Santana Row', 'Ste 1090', 'San Jose, CA 95128'],
      },
      phone: '+14082447001',
      display_phone: '(408) 244-7001',
      distance: 5740.682553656406,
    },
    {
      id: 'PoqyugcuH71tkEwXnDcmYQ',
      alias: 'mizu-sushi-bar-and-grill-san-jose',
      name: 'Mizu Sushi Bar & Grill',
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/nvj_LEnUxrc39HCRexva0A/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/mizu-sushi-bar-and-grill-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 3185,
      categories: [
        {
          alias: 'sushi',
          title: 'Sushi Bars',
        },
        {
          alias: 'japanese',
          title: 'Japanese',
        },
        {
          alias: 'korean',
          title: 'Korean',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.30805,
        longitude: -121.95056,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$$',
      location: {
        address1: '1035 S Winchester Blvd',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95128',
        country: 'US',
        state: 'CA',
        display_address: ['1035 S Winchester Blvd', 'San Jose, CA 95128'],
      },
      phone: '+14082607200',
      display_phone: '(408) 260-7200',
      distance: 5860.180238306413,
    },
    {
      id: 'zLViW6kDKNLIYsGkBCNorg',
      alias: 'paesano-ristorante-italiano-san-jose',
      name: 'Paesano Ristorante Italiano',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/oDYRK0KAZ7Le47ZhDDt0ag/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/paesano-ristorante-italiano-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1311,
      categories: [
        {
          alias: 'italian',
          title: 'Italian',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.336166540678,
        longitude: -121.89867135144,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '350 W Julian St',
        address2: 'Ste 1',
        address3: '',
        city: 'San Jose',
        zip_code: '95110',
        country: 'US',
        state: 'CA',
        display_address: ['350 W Julian St', 'Ste 1', 'San Jose, CA 95110'],
      },
      phone: '+14082179327',
      display_phone: '(408) 217-9327',
      distance: 2489.5832249207588,
    },
    {
      id: 'MRlHo4kxMHRVj5iUyvxZQA',
      alias: 'yard-house-san-jose-4',
      name: 'Yard House',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/EQqRjqYV6fbZDYM1GX6WuQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/yard-house-san-jose-4?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 4291,
      categories: [
        {
          alias: 'newamerican',
          title: 'New American',
        },
        {
          alias: 'vegetarian',
          title: 'Vegetarian',
        },
        {
          alias: 'bars',
          title: 'Bars',
        },
      ],
      rating: 3.5,
      coordinates: {
        latitude: 37.3229817029011,
        longitude: -121.947494338623,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '300 Santana Row',
        address2: 'Ste 101',
        address3: '',
        city: 'San Jose',
        zip_code: '95128',
        country: 'US',
        state: 'CA',
        display_address: ['300 Santana Row', 'Ste 101', 'San Jose, CA 95128'],
      },
      phone: '+14082419273',
      display_phone: '(408) 241-9273',
      distance: 5568.879787063705,
    },
    {
      id: '7jidkejbcWaRsPhquW56lQ',
      alias: 'le-papillon-san-jose',
      name: 'Le Papillon',
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/_VGkXA7Z_dlxi2jlRa98Lg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/le-papillon-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1215,
      categories: [
        {
          alias: 'french',
          title: 'French',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.31975,
        longitude: -121.97232,
      },
      transactions: ['pickup'],
      price: '$$$$',
      location: {
        address1: '410 Saratoga Ave',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95129',
        country: 'US',
        state: 'CA',
        display_address: ['410 Saratoga Ave', 'San Jose, CA 95129'],
      },
      phone: '+14082963730',
      display_phone: '(408) 296-3730',
      distance: 7737.461608176978,
    },
    {
      id: 'Mvbq_Ai-QvIx7ceIUtC4pg',
      alias: 'mariscos-costa-alegre-san-jose',
      name: 'Mariscos Costa Alegre',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/kEJYTWSoboPibwp9a1PuTw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/mariscos-costa-alegre-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 661,
      categories: [
        {
          alias: 'seafood',
          title: 'Seafood',
        },
        {
          alias: 'mexican',
          title: 'Mexican',
        },
        {
          alias: 'sushi',
          title: 'Sushi Bars',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.35830364607693,
        longitude: -121.8905692,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '855 N13th St',
        address2: null,
        address3: '',
        city: 'San Jose',
        zip_code: '95112',
        country: 'US',
        state: 'CA',
        display_address: ['855 N13th St', 'San Jose, CA 95112'],
      },
      phone: '+14082805014',
      display_phone: '(408) 280-5014',
      distance: 4665.404833488967,
    },
    {
      id: 'I-1l3unxDVaEOpUqSgNj1A',
      alias: 'tostadas-san-jose',
      name: 'Tostadas',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/eAPbEQgBv9UBZp9IXgucPQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/tostadas-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1588,
      categories: [
        {
          alias: 'breakfast_brunch',
          title: 'Breakfast & Brunch',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.33914669939744,
        longitude: -121.88395663107823,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '304 E Santa Clara St',
        address2: 'Ste A',
        address3: null,
        city: 'San Jose',
        zip_code: '95112',
        country: 'US',
        state: 'CA',
        display_address: ['304 E Santa Clara St', 'Ste A', 'San Jose, CA 95112'],
      },
      phone: '',
      display_phone: '',
      distance: 2511.3456494710213,
    },
    {
      id: 'ozgoYrwfc4te-teWmegM_g',
      alias: 'udon-mugizo-san-jose-san-jose',
      name: 'Udon Mugizo - San Jose',
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/2fS4QYadN_qCwGjuLc5w4Q/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/udon-mugizo-san-jose-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 750,
      categories: [
        {
          alias: 'japanese',
          title: 'Japanese',
        },
        {
          alias: 'noodles',
          title: 'Noodles',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.306511102886255,
        longitude: -121.9775689624031,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '1072 Saratoga Ave',
        address2: '',
        address3: null,
        city: 'San Jose',
        zip_code: '95129',
        country: 'US',
        state: 'CA',
        display_address: ['1072 Saratoga Ave', 'San Jose, CA 95129'],
      },
      phone: '+14083202291',
      display_phone: '(408) 320-2291',
      distance: 8259.741795425945,
    },
    {
      id: 'lPkQK2N4g658SR_7BBxeaQ',
      alias: 'peters-bakery-san-jose-2',
      name: "Peters' Bakery",
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/RCy13tZ_g7V4NtkOwnZ4fg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/peters-bakery-san-jose-2?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 2362,
      categories: [
        {
          alias: 'bakeries',
          title: 'Bakeries',
        },
        {
          alias: 'donuts',
          title: 'Donuts',
        },
        {
          alias: 'cupcakes',
          title: 'Cupcakes',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.36573,
        longitude: -121.82734,
      },
      transactions: ['pickup'],
      price: '$$',
      location: {
        address1: '3108 Alum Rock Ave',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95127',
        country: 'US',
        state: 'CA',
        display_address: ['3108 Alum Rock Ave', 'San Jose, CA 95127'],
      },
      phone: '+14082583529',
      display_phone: '(408) 258-3529',
      distance: 7467.5462212380635,
    },
    {
      id: '7NOpkoAUAGqMKEZgSu1QmA',
      alias: 'a-slice-of-new-york-san-jose',
      name: 'A Slice of New York',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/aTipilLBRg2sYIPF1eOf1A/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/a-slice-of-new-york-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 3372,
      categories: [
        {
          alias: 'pizza',
          title: 'Pizza',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.3235243214913,
        longitude: -121.959063137967,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '3443 Stevens Creek Blvd',
        address2: null,
        address3: '',
        city: 'San Jose',
        zip_code: '95117',
        country: 'US',
        state: 'CA',
        display_address: ['3443 Stevens Creek Blvd', 'San Jose, CA 95117'],
      },
      phone: '+14082475423',
      display_phone: '(408) 247-5423',
      distance: 6591.5760260939605,
    },
    {
      id: 'sUrNF-1HaZ-kGRqzZljVEQ',
      alias: 'the-cider-junction-san-jose-5',
      name: 'The Cider Junction',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/3QJzAvY278mIqZDyju1JSw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/the-cider-junction-san-jose-5?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 315,
      categories: [
        {
          alias: 'cideries',
          title: 'Cideries',
        },
        {
          alias: 'comfortfood',
          title: 'Comfort Food',
        },
        {
          alias: 'beergardens',
          title: 'Beer Gardens',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.310547,
        longitude: -121.895777,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '820 Willow St',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95125',
        country: 'US',
        state: 'CA',
        display_address: ['820 Willow St', 'San Jose, CA 95125'],
      },
      phone: '+16692342751',
      display_phone: '(669) 234-2751',
      distance: 1164.5565620084749,
    },
    {
      id: 'vZ41QYMBQvtHgpAfw1IToQ',
      alias: 'pizza-antica-san-jose',
      name: 'Pizza Antica',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/4HdmFLHYUunTlIi-B_vIuQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/pizza-antica-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 3329,
      categories: [
        {
          alias: 'pizza',
          title: 'Pizza',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.322020736453815,
        longitude: -121.94757693252252,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '334 Santana Row',
        address2: 'Ste 1065',
        address3: '',
        city: 'San Jose',
        zip_code: '95128',
        country: 'US',
        state: 'CA',
        display_address: ['334 Santana Row', 'Ste 1065', 'San Jose, CA 95128'],
      },
      phone: '+14085578373',
      display_phone: '(408) 557-8373',
      distance: 5563.5230037550955,
    },
    {
      id: 'VUHVTQl8sWTAwtGcnfbRDw',
      alias: 'island-taste-caribbean-grill-san-jose-2',
      name: 'Island Taste Caribbean Grill',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/bcM4LEKQ2BpDHzO5ruldwA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/island-taste-caribbean-grill-san-jose-2?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 228,
      categories: [
        {
          alias: 'caribbean',
          title: 'Caribbean',
        },
        {
          alias: 'chicken_wings',
          title: 'Chicken Wings',
        },
        {
          alias: 'soulfood',
          title: 'Soul Food',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.33865,
        longitude: -121.88585,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '225 E Santa Clara St',
        address2: '',
        address3: null,
        city: 'San Jose',
        zip_code: '95112',
        country: 'US',
        state: 'CA',
        display_address: ['225 E Santa Clara St', 'San Jose, CA 95112'],
      },
      phone: '+16698991097',
      display_phone: '(669) 899-1097',
      distance: 2446.6113518682273,
    },
    {
      id: 'jfMK6n5Mln7ilco6r2YXoA',
      alias: 'qpot-san-jose-2',
      name: 'QPOT',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/8H4Wg87Nq9p7lNV9aWX7XA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/qpot-san-jose-2?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 3876,
      categories: [
        {
          alias: 'korean',
          title: 'Korean',
        },
        {
          alias: 'hotpot',
          title: 'Hot Pot',
        },
        {
          alias: 'bbq',
          title: 'Barbeque',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.305813,
        longitude: -121.812039,
      },
      transactions: ['pickup'],
      price: '$$',
      location: {
        address1: '1610 E Capitol Expy',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95121',
        country: 'US',
        state: 'CA',
        display_address: ['1610 E Capitol Expy', 'San Jose, CA 95121'],
      },
      phone: '+16692343095',
      display_phone: '(669) 234-3095',
      distance: 6565.816895646217,
    },
    {
      id: 'DvBxmtOxSl66U-Qb_Rkv1w',
      alias: 'braise-willow-glen-san-jose',
      name: 'Braise Willow Glen',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/KQIz4yEQhWSePthEqmpLKg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/braise-willow-glen-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 462,
      categories: [
        {
          alias: 'newamerican',
          title: 'New American',
        },
        {
          alias: 'cocktailbars',
          title: 'Cocktail Bars',
        },
        {
          alias: 'burgers',
          title: 'Burgers',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.30686,
        longitude: -121.90035,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '1185 Lincoln Ave',
        address2: '',
        address3: null,
        city: 'San Jose',
        zip_code: '95125',
        country: 'US',
        state: 'CA',
        display_address: ['1185 Lincoln Ave', 'San Jose, CA 95125'],
      },
      phone: '+14082942919',
      display_phone: '(408) 294-2919',
      distance: 1731.398351052876,
    },
    {
      id: '2cZKrmNPpFhEGsTOWDGuDw',
      alias: 'ozumo-santana-row-san-jose-2',
      name: 'Ozumo Santana Row',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/ZSnQA6cj18qB3U8s4NJPpw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/ozumo-santana-row-san-jose-2?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1455,
      categories: [
        {
          alias: 'izakaya',
          title: 'Izakaya',
        },
        {
          alias: 'sushi',
          title: 'Sushi Bars',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3210174176298,
        longitude: -121.948078443517,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$$',
      location: {
        address1: '355 Santana Row',
        address2: 'Ste 1010',
        address3: '',
        city: 'San Jose',
        zip_code: '95128',
        country: 'US',
        state: 'CA',
        display_address: ['355 Santana Row', 'Ste 1010', 'San Jose, CA 95128'],
      },
      phone: '+14088863090',
      display_phone: '(408) 886-3090',
      distance: 5596.7058089150105,
    },
    {
      id: 'x0DX2qsBTikXJSDRVex15Q',
      alias: 'jubba-restaurant-san-jose',
      name: 'Jubba Restaurant',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/RLoCRlKZMKtn_uV78qtJ4A/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/jubba-restaurant-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1392,
      categories: [
        {
          alias: 'halal',
          title: 'Halal',
        },
        {
          alias: 'somali',
          title: 'Somali',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.257396,
        longitude: -121.860752,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '5330 Terner Way',
        address2: 'Ste 40',
        address3: '',
        city: 'San Jose',
        zip_code: '95136',
        country: 'US',
        state: 'CA',
        display_address: ['5330 Terner Way', 'Ste 40', 'San Jose, CA 95136'],
      },
      phone: '+14084401504',
      display_phone: '(408) 440-1504',
      distance: 6922.5138352037075,
    },
    {
      id: 'xjMeVFpOFtGsSqgWYMs9Qg',
      alias: 'zona-rosa-san-jose',
      name: 'Zona Rosa',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/YJXJGM9Y4LEvgOb6BwQZcg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/zona-rosa-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1543,
      categories: [
        {
          alias: 'mexican',
          title: 'Mexican',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3330684770691,
        longitude: -121.914127461814,
      },
      transactions: ['delivery', 'pickup', 'restaurant_reservation'],
      price: '$$',
      location: {
        address1: '1411 The Alameda',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95126',
        country: 'US',
        state: 'CA',
        display_address: ['1411 The Alameda', 'San Jose, CA 95126'],
      },
      phone: '+14082751411',
      display_phone: '(408) 275-1411',
      distance: 3159.0355284951443,
    },
    {
      id: 'vtGDGnmACWtZPJR2i0q54A',
      alias: 'jackies-place-san-jose',
      name: "Jackie's Place",
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/HAGJsU8qOir5qvMjr8vO3Q/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/jackies-place-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1308,
      categories: [
        {
          alias: 'soulfood',
          title: 'Soul Food',
        },
        {
          alias: 'bbq',
          title: 'Barbeque',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.35222,
        longitude: -121.90215,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '840 North 1st St',
        address2: null,
        address3: '',
        city: 'San Jose',
        zip_code: '95112',
        country: 'US',
        state: 'CA',
        display_address: ['840 North 1st St', 'San Jose, CA 95112'],
      },
      phone: '+14084904653',
      display_phone: '(408) 490-4653',
      distance: 4243.260868904926,
    },
    {
      id: 'IbOKhiMc9ciqgSjLBUnSIg',
      alias: 'pho-ha-noi-san-jose-6',
      name: 'Pho Ha Noi',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/Daf9IwA6OgtXrFEk_kxJFQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/pho-ha-noi-san-jose-6?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1648,
      categories: [
        {
          alias: 'vietnamese',
          title: 'Vietnamese',
        },
        {
          alias: 'noodles',
          title: 'Noodles',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.332157,
        longitude: -121.858136,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '969 Story Rd',
        address2: 'Ste 6048',
        address3: null,
        city: 'San Jose',
        zip_code: '95122',
        country: 'US',
        state: 'CA',
        display_address: ['969 Story Rd', 'Ste 6048', 'San Jose, CA 95122'],
      },
      phone: '+14082390888',
      display_phone: '(408) 239-0888',
      distance: 2919.488017860488,
    },
    {
      id: 'Kch4seq9jJ_nuNsHcWUgcA',
      alias: 'lazy-dog-restaurant-and-bar-san-jose-3',
      name: 'Lazy Dog Restaurant & Bar',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/FXFZYoj_HMM5al2xsecnhg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/lazy-dog-restaurant-and-bar-san-jose-3?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 567,
      categories: [
        {
          alias: 'comfortfood',
          title: 'Comfort Food',
        },
        {
          alias: 'newamerican',
          title: 'New American',
        },
        {
          alias: 'burgers',
          title: 'Burgers',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.253539,
        longitude: -121.876352,
      },
      transactions: [],
      price: '$$',
      location: {
        address1: '5305 Almaden Expy',
        address2: '',
        address3: null,
        city: 'San Jose',
        zip_code: '95118',
        country: 'US',
        state: 'CA',
        display_address: ['5305 Almaden Expy', 'San Jose, CA 95118'],
      },
      phone: '+14087869594',
      display_phone: '(408) 786-9594',
      distance: 7049.326179591731,
    },
    {
      id: 'berEiBE0fDM-HiYFEAf-Ww',
      alias: 'goodtime-bar-san-jose',
      name: 'Goodtime Bar',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/cCukHjg_K6TDMO7F5VQWsQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/goodtime-bar-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 73,
      categories: [
        {
          alias: 'wine_bars',
          title: 'Wine Bars',
        },
        {
          alias: 'tapasmallplates',
          title: 'Tapas/Small Plates',
        },
        {
          alias: 'seafood',
          title: 'Seafood',
        },
      ],
      rating: 5.0,
      coordinates: {
        latitude: 37.336063871551694,
        longitude: -121.8896383855525,
      },
      transactions: [],
      price: '$$',
      location: {
        address1: '30 Fountain Aly',
        address2: 'Ste 160',
        address3: null,
        city: 'San Jose',
        zip_code: '95113',
        country: 'US',
        state: 'CA',
        display_address: ['30 Fountain Aly', 'Ste 160', 'San Jose, CA 95113'],
      },
      phone: '+14082561266',
      display_phone: '(408) 256-1266',
      distance: 2204.627239974566,
    },
    {
      id: 'DSTcStaxO2MxG1xRx4by3A',
      alias: 'toast-cafe-and-grill-san-jose-2',
      name: 'Toast Cafe & Grill',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/xnfKkZMLYzef5VU6JzCVig/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/toast-cafe-and-grill-san-jose-2?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1481,
      categories: [
        {
          alias: 'breakfast_brunch',
          title: 'Breakfast & Brunch',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.30672959520548,
        longitude: -121.89179398749884,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '1411 Bird Ave',
        address2: '',
        address3: null,
        city: 'San Jose',
        zip_code: '95125',
        country: 'US',
        state: 'CA',
        display_address: ['1411 Bird Ave', 'San Jose, CA 95125'],
      },
      phone: '+14083201575',
      display_phone: '(408) 320-1575',
      distance: 1247.5729592173568,
    },
    {
      id: 'jw7wkWmTX04fRYLcp9vlPQ',
      alias: 'falafels-drive-in-san-jose',
      name: "Falafel's Drive-In",
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/4HRlmRid5oIoIjVTQB5Dlg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/falafels-drive-in-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 5239,
      categories: [
        {
          alias: 'mideastern',
          title: 'Middle Eastern',
        },
        {
          alias: 'falafel',
          title: 'Falafel',
        },
        {
          alias: 'hotdogs',
          title: 'Fast Food',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.323719276993586,
        longitude: -121.93508055499372,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '2301 Stevens Creek Blvd',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95128',
        country: 'US',
        state: 'CA',
        display_address: ['2301 Stevens Creek Blvd', 'San Jose, CA 95128'],
      },
      phone: '+14082947886',
      display_phone: '(408) 294-7886',
      distance: 4496.084042426032,
    },
    {
      id: '28W6LDX-iXnSiim4ZClrYw',
      alias: '55-south-san-jose',
      name: '55 South',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/3WENV3DRIOSfQ6FWCQcXqA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/55-south-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 738,
      categories: [
        {
          alias: 'lounges',
          title: 'Lounges',
        },
        {
          alias: 'newamerican',
          title: 'New American',
        },
        {
          alias: 'cocktailbars',
          title: 'Cocktail Bars',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.33503,
        longitude: -121.89013,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '55 S 1st St',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95113',
        country: 'US',
        state: 'CA',
        display_address: ['55 S 1st St', 'San Jose, CA 95113'],
      },
      phone: '+14082886000',
      display_phone: '(408) 288-6000',
      distance: 2109.3086267688377,
    },
    {
      id: 'kRxv3REQDh1tY2OfI8Z7uw',
      alias: 'petiscos-san-jose',
      name: 'Petiscos',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/TTRyBVAx3XRwkBXS89W4jg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/petiscos-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 462,
      categories: [
        {
          alias: 'portuguese',
          title: 'Portuguese',
        },
        {
          alias: 'tapasmallplates',
          title: 'Tapas/Small Plates',
        },
        {
          alias: 'seafood',
          title: 'Seafood',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.330018,
        longitude: -121.886354,
      },
      transactions: [],
      price: '$$$',
      location: {
        address1: '399 S 1st St',
        address2: '',
        address3: null,
        city: 'San Jose',
        zip_code: '95113',
        country: 'US',
        state: 'CA',
        display_address: ['399 S 1st St', 'San Jose, CA 95113'],
      },
      phone: '+14083202884',
      display_phone: '(408) 320-2884',
      distance: 1504.685462417027,
    },
    {
      id: '-A2EzuWuOhzGW2mkzr9sLg',
      alias: 'the-city-fish-san-jose',
      name: 'The City Fish',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/VmKCPAJWZzkBxGFOWApBHQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/the-city-fish-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1277,
      categories: [
        {
          alias: 'seafood',
          title: 'Seafood',
        },
        {
          alias: 'fishnchips',
          title: 'Fish & Chips',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.33638,
        longitude: -121.88988,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '30 E Santa Clara St',
        address2: 'Ste 140',
        address3: '',
        city: 'San Jose',
        zip_code: '95113',
        country: 'US',
        state: 'CA',
        display_address: ['30 E Santa Clara St', 'Ste 140', 'San Jose, CA 95113'],
      },
      phone: '+14082933474',
      display_phone: '(408) 293-3474',
      distance: 2243.1654720874685,
    },
    {
      id: 'UPjhJoqpbJr0u8mvTOxneQ',
      alias: 'sj-omogari-san-jose-3',
      name: 'SJ Omogari',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/0jkgYExp5QBYqf2kZ2SygQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/sj-omogari-san-jose-3?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 2473,
      categories: [
        {
          alias: 'korean',
          title: 'Korean',
        },
        {
          alias: 'soup',
          title: 'Soup',
        },
        {
          alias: 'seafood',
          title: 'Seafood',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.348433,
        longitude: -121.895124,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '154 Jackson St',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95112',
        country: 'US',
        state: 'CA',
        display_address: ['154 Jackson St', 'San Jose, CA 95112'],
      },
      phone: '+14082888134',
      display_phone: '(408) 288-8134',
      distance: 3652.6961387694555,
    },
    {
      id: 'xTGBbaEEgm4pB5DgN88qZQ',
      alias: 'the-funny-farm-san-jose-3',
      name: 'The Funny Farm',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/iMFixL9jfeiQymaknsEXQQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/the-funny-farm-san-jose-3?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 976,
      categories: [
        {
          alias: 'burgers',
          title: 'Burgers',
        },
        {
          alias: 'chicken_wings',
          title: 'Chicken Wings',
        },
        {
          alias: 'breakfast_brunch',
          title: 'Breakfast & Brunch',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.300102,
        longitude: -121.771571,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '4898 San Felipe Rd',
        address2: 'Ste 150',
        address3: '',
        city: 'San Jose',
        zip_code: '95135',
        country: 'US',
        state: 'CA',
        display_address: ['4898 San Felipe Rd', 'Ste 150', 'San Jose, CA 95135'],
      },
      phone: '+14086226953',
      display_phone: '(408) 622-6953',
      distance: 10205.365523470351,
    },
    {
      id: '7juJxsuoqYvWa9om6EcxsQ',
      alias: 'bun-bo-hue-an-nam-san-jose',
      name: 'Bun Bo Hue An Nam',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/XyzJs3Vv-dSyWZWGWCxL-Q/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/bun-bo-hue-an-nam-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 2166,
      categories: [
        {
          alias: 'vietnamese',
          title: 'Vietnamese',
        },
        {
          alias: 'soup',
          title: 'Soup',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.32889433672542,
        longitude: -121.85828957414292,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '740 Story Rd',
        address2: 'Ste 3',
        address3: '',
        city: 'San Jose',
        zip_code: '95122',
        country: 'US',
        state: 'CA',
        display_address: ['740 Story Rd', 'Ste 3', 'San Jose, CA 95122'],
      },
      phone: '+14089931755',
      display_phone: '(408) 993-1755',
      distance: 2732.9568669911787,
    },
    {
      id: 'BwCVx1z-W0foNZHfsBKmzw',
      alias: 'santo-market-san-jose-3',
      name: 'Santo Market',
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/0mYASZYiFOx1pWShvyWBAw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/santo-market-san-jose-3?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 823,
      categories: [
        {
          alias: 'delis',
          title: 'Delis',
        },
        {
          alias: 'intlgrocery',
          title: 'International Grocery',
        },
        {
          alias: 'sandwiches',
          title: 'Sandwiches',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.35171,
        longitude: -121.89533,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '245 E Taylor St',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95112',
        country: 'US',
        state: 'CA',
        display_address: ['245 E Taylor St', 'San Jose, CA 95112'],
      },
      phone: '+14082955406',
      display_phone: '(408) 295-5406',
      distance: 4010.4098122722,
    },
    {
      id: 'nxaeQ0in8V1eFzxRMfAyJw',
      alias: 'meso-modern-mediterranean-san-jose-2',
      name: 'Meso Modern Mediterranean',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/RO_sxXWw5z_0bX3jM-kHxA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/meso-modern-mediterranean-san-jose-2?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 800,
      categories: [
        {
          alias: 'mediterranean',
          title: 'Mediterranean',
        },
        {
          alias: 'cocktailbars',
          title: 'Cocktail Bars',
        },
        {
          alias: 'mideastern',
          title: 'Middle Eastern',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.31904386630844,
        longitude: -121.94823753823546,
      },
      transactions: ['delivery'],
      price: '$$$',
      location: {
        address1: '3060 Olsen Dr',
        address2: 'Ste 50',
        address3: null,
        city: 'San Jose',
        zip_code: '95128',
        country: 'US',
        state: 'CA',
        display_address: ['3060 Olsen Dr', 'Ste 50', 'San Jose, CA 95128'],
      },
      phone: '+14088000048',
      display_phone: '(408) 800-0048',
      distance: 5595.756793656189,
    },
    {
      id: 'AUo3AVgAiEfl9icvM57aaA',
      alias: 'district-san-jose-san-jose',
      name: 'District - San Jose',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/vtrECsbd4BIxuaq8yy9gRw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/district-san-jose-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 484,
      categories: [
        {
          alias: 'tapasmallplates',
          title: 'Tapas/Small Plates',
        },
        {
          alias: 'wine_bars',
          title: 'Wine Bars',
        },
        {
          alias: 'whiskeybars',
          title: 'Whiskey Bars',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.336178007464,
        longitude: -121.893876187673,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '65 N San Pedro St',
        address2: '',
        address3: null,
        city: 'San Jose',
        zip_code: '95110',
        country: 'US',
        state: 'CA',
        display_address: ['65 N San Pedro St', 'San Jose, CA 95110'],
      },
      phone: '+16692925252',
      display_phone: '(669) 292-5252',
      distance: 2315.371573057313,
    },
    {
      id: '01Ef5b0clhpv3RYuAR1HCw',
      alias: 'vin-santo-ristorante-san-jose',
      name: 'Vin Santo Ristorante',
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/mvqKbpJKoA5ipSZWm-qKVQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/vin-santo-ristorante-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 859,
      categories: [
        {
          alias: 'italian',
          title: 'Italian',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.304512408122,
        longitude: -121.89778667565,
      },
      transactions: ['delivery', 'pickup', 'restaurant_reservation'],
      price: '$$',
      location: {
        address1: '1346 Lincoln Ave',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95125',
        country: 'US',
        state: 'CA',
        display_address: ['1346 Lincoln Ave', 'San Jose, CA 95125'],
      },
      phone: '+14083525564',
      display_phone: '(408) 352-5564',
      distance: 1752.6100268203472,
    },
    {
      id: 'nHLD88-716MTMoV1kjK-wQ',
      alias: 'smoking-pig-bbq-san-jose',
      name: 'Smoking Pig BBQ',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/YX_U2evQsBK7pzm8HIyUzA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/smoking-pig-bbq-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 3389,
      categories: [
        {
          alias: 'bbq',
          title: 'Barbeque',
        },
        {
          alias: 'southern',
          title: 'Southern',
        },
        {
          alias: 'tradamerican',
          title: 'American',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.35875,
        longitude: -121.9027,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '1144 N 4th St',
        address2: '',
        address3: '',
        city: 'San Jose',
        zip_code: '95112',
        country: 'US',
        state: 'CA',
        display_address: ['1144 N 4th St', 'San Jose, CA 95112'],
      },
      phone: '+14083804784',
      display_phone: '(408) 380-4784',
      distance: 4958.521725023926,
    },
    {
      id: 'CTbh1zm-SsVVEmSxVexaTA',
      alias: 'little-wine-house-san-jose',
      name: 'Little Wine House',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/LtEDLuzoDiY0ujxLRvY0ag/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/little-wine-house-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 93,
      categories: [
        {
          alias: 'wine_bars',
          title: 'Wine Bars',
        },
        {
          alias: 'beerbar',
          title: 'Beer Bar',
        },
        {
          alias: 'tapas',
          title: 'Tapas Bars',
        },
      ],
      rating: 5.0,
      coordinates: {
        latitude: 37.33574,
        longitude: -121.89884,
      },
      transactions: [],
      price: '$$',
      location: {
        address1: '350 W Julian St',
        address2: 'Bldg 4',
        address3: '',
        city: 'San Jose',
        zip_code: '95110',
        country: 'US',
        state: 'CA',
        display_address: ['350 W Julian St', 'Bldg 4', 'San Jose, CA 95110'],
      },
      phone: '+14084718039',
      display_phone: '(408) 471-8039',
      distance: 2462.029637465616,
    },
    {
      id: 'zYljE3M9zSoZdipfFQidpA',
      alias: 'the-boiling-crab-san-jose',
      name: 'The Boiling Crab',
      image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/XbApEPGIqNxBdL7UzC0flw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/the-boiling-crab-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 4165,
      categories: [
        {
          alias: 'cajun',
          title: 'Cajun/Creole',
        },
        {
          alias: 'seafood',
          title: 'Seafood',
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.30656,
        longitude: -121.81228,
      },
      transactions: ['delivery'],
      price: '$$',
      location: {
        address1: '1631 E Capitol Expy',
        address2: 'Ste 101',
        address3: '',
        city: 'San Jose',
        zip_code: '95121',
        country: 'US',
        state: 'CA',
        display_address: ['1631 E Capitol Expy', 'Ste 101', 'San Jose, CA 95121'],
      },
      phone: '+14085326147',
      display_phone: '(408) 532-6147',
      distance: 6533.572177366097,
    },
    {
      id: 'QNzqZtNb_I1mcHAviE5zeQ',
      alias: 'bibos-ny-pizza-san-jose',
      name: "Bibo's Ny Pizza",
      image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/slNv72CZB3njkm6xSe0_yA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/bibos-ny-pizza-san-jose?adjust_creative=qoIeKDIshPCsdoJmnPOyLg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qoIeKDIshPCsdoJmnPOyLg',
      review_count: 1416,
      categories: [
        {
          alias: 'pizza',
          title: 'Pizza',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.306477955952,
        longitude: -121.89160958914,
      },
      transactions: ['pickup'],
      price: '$$',
      location: {
        address1: '1431 Bird Ave',
        address2: null,
        address3: '',
        city: 'San Jose',
        zip_code: '95125',
        country: 'US',
        state: 'CA',
        display_address: ['1431 Bird Ave', 'San Jose, CA 95125'],
      },
      phone: '+14082179084',
      display_phone: '(408) 217-9084',
      distance: 1264.6251986624127,
    },
  ],
  total: 4800,
  region: {
    center: {
      longitude: -121.88507080078125,
      latitude: 37.31648115417059,
    },
  },
};

export default testData;
